import React, { createContext, useContext, useState, ReactNode } from 'react';

type LanguageCode = 'en' | 'ms' | 'zh' | 'yue' | 'ja' | 'id' | 'ru' | 'de';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const dictionaries: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & Titles
    dashboard: "Dashboard",
    generator: "Voucher Generator",
    history: "History",
    lhdnLetter: "LHDN Letter",
    aiAdvisor: "AI Advisor",
    liveAgent: "Live Agent",
    receiptEditor: "Receipt Editor",
    settings: "Settings",
    appTitle1: "TUNAI",
    appTitle2: "CUKAI",
    
    // Voucher Generator
    newVoucher: "New Cash Voucher",
    newVoucherDesc: "Generate a new payment voucher with AI assistance",
    uploadReceipt: "Upload Receipt",
    readAloud: "Read Aloud",
    companyInfo: "Company Information",
    companyName: "Company Name",
    regNo: "Registration No",
    address: "Address",
    tel: "Tel",
    email: "Email",
    voucherDetails: "Voucher Details",
    voucherNo: "Voucher No.",
    voucherDate: "Voucher Date",
    category: "Category",
    payeeInfo: "Payee & Payment Info",
    payeeName: "Payee Name",
    payeeIc: "Payee IC/Reg",
    paymentMethod: "Payment Method",
    bankName: "Bank Name",
    desc: "Description",
    dictate: "Dictate",
    stop: "Stop",
    aiSummarize: "AI Summarize",
    taxCompliance: "Tax Compliance",
    lineItems: "Line Items",
    addItem: "Add Item",
    summary: "Summary",
    totalAmount: "Total Amount",
    save: "Save",
    previewPdf: "Preview PDF",
    downloadPdf: "Download PDF",
    complianceProgress: "Compliance Progress",

    // Errors & OCR
    scanFailed: "Scan Failed",
    unclearDoc: "Unclear Document",
    unclearDocDesc: "Could not identify clear text. Ensure the image is well-lit and legible.",
    authFailed: "Authorization Failed",
    authFailedDesc: "Invalid or missing API Key. Please check Settings.",
    quotaExceeded: "Quota Exceeded",
    quotaExceededDesc: "You have reached the request limit for the API. Please try again later.",
    serviceUnavailable: "Service Unavailable",
    serviceUnavailableDesc: "The AI service is currently busy. Please try again in a moment.",
    connError: "Connection Error",
    connErrorDesc: "Unable to reach the server. Please check your internet connection.",
    contentFiltered: "Content Filtered",
    contentFilteredDesc: "The image was flagged by safety filters. Please try another image.",
    processingError: "Processing Error",
    processingErrorDesc: "An unexpected error occurred. Please try again.",
    unsupportedFile: "Unsupported File",
    unsupportedFileDesc: "Please upload a JPEG, PNG, or WebP image.",
    fileTooLarge: "File Too Large",
    fileTooLargeDesc: "Please upload an image smaller than 10MB.",

    // Dashboard
    totalExpenses: "Total Expenses",
    pendingVouchers: "Pending Vouchers",
    aiOptimizations: "AI Optimizations",
    recentActivity: "Recent Activity",
    aiInsights: "AI Insights",
    expenditure: "Expenditure",
    taxDeductibility: "Tax Deductibility",
    weekly: "Weekly",
    annually: "Annually",
    taxFiling: "LHDN Tax Filing (e-B)",
    daysLeft: "Days Left",
    actionRequired: "Action Required",
    
    // Live Agent
    startSession: "Start Voice Session",
    establishingLink: "Establishing Link...",
    listening: "Listening & Watching...",
    speaking: "Gemini is speaking...",
    connect: "Connect Live Agent",
    endSession: "End Session",
    liveLogs: "Live Logs",
    spatialAwareness: "Spatial Awareness Active",
    
    // Settings
    generalApiConfig: "General API Configuration",
    apiKeyLabel: "Google Gemini API Key",
    apiKeyDesc: "This master key enables all AI features including OCR, Live Agent, and Image Editing.",
    saveConnect: "Save & Connect",
    serviceStatus: "Service Status",
    active: "Active",
    inactive: "Inactive",
    ocrEngine: "OCR Engine",
    advisorChat: "Advisor Chat",
    
    // Receipt Editor
    uploadImage: "Upload Image",
    editorPrompt: "Editor Prompt",
    enableTranslation: "Enable Translation",
    targetLanguage: "Target Language",
    generateEdit: "Generate Edit",
    generateTranslate: "Generate & Translate",
    downloadResult: "Download Result"
  },
  ms: {
    dashboard: "Papan Pemuka",
    generator: "Penjana Baucar",
    history: "Sejarah",
    lhdnLetter: "Surat LHDN",
    aiAdvisor: "Penasihat AI",
    liveAgent: "Ejen Langsung",
    receiptEditor: "Editor Resit",
    settings: "Tetapan",
    appTitle1: "TUNAI",
    appTitle2: "CUKAI",
    newVoucher: "Baucar Tunai Baharu",
    newVoucherDesc: "Jana baucar pembayaran baharu dengan bantuan AI",
    uploadReceipt: "Muat Naik Resit",
    readAloud: "Baca Kuat",
    companyInfo: "Maklumat Syarikat",
    companyName: "Nama Syarikat",
    regNo: "No. Pendaftaran",
    address: "Alamat",
    tel: "Tel",
    email: "Emel",
    voucherDetails: "Butiran Baucar",
    voucherNo: "No. Baucar",
    voucherDate: "Tarikh Baucar",
    category: "Kategori",
    payeeInfo: "Maklumat Penerima & Bayaran",
    payeeName: "Nama Penerima",
    payeeIc: "KP/Reg Penerima",
    paymentMethod: "Kaedah Bayaran",
    bankName: "Nama Bank",
    desc: "Keterangan",
    dictate: "Dikte",
    stop: "Berhenti",
    aiSummarize: "Ringkasan AI",
    taxCompliance: "Pematuhan Cukai",
    lineItems: "Item Baris",
    addItem: "Tambah Item",
    summary: "Ringkasan",
    totalAmount: "Jumlah Besar",
    save: "Simpan",
    previewPdf: "Pratonton PDF",
    downloadPdf: "Muat Turun PDF",
    complianceProgress: "Kemajuan Pematuhan",
    scanFailed: "Imbasan Gagal",
    unclearDoc: "Dokumen Tidak Jelas",
    unclearDocDesc: "Teks tidak dapat dikenal pasti. Pastikan imej terang dan jelas.",
    authFailed: "Pengesahan Gagal",
    authFailedDesc: "Kunci API tidak sah atau hilang. Sila semak Tetapan.",
    quotaExceeded: "Kuota Melebihi Had",
    quotaExceededDesc: "Anda telah mencapai had permintaan API. Sila cuba lagi kemudian.",
    serviceUnavailable: "Perkhidmatan Tidak Tersedia",
    serviceUnavailableDesc: "Perkhidmatan AI sedang sibuk. Sila cuba sebentar lagi.",
    connError: "Ralat Sambungan",
    connErrorDesc: "Tidak dapat menyambung ke pelayan. Sila semak sambungan internet anda.",
    contentFiltered: "Kandungan Ditapis",
    contentFilteredDesc: "Imej telah ditapis atas sebab keselamatan. Sila cuba imej lain.",
    processingError: "Ralat Pemprosesan",
    processingErrorDesc: "Ralat tidak dijangka berlaku. Sila cuba lagi.",
    unsupportedFile: "Fail Tidak Disokong",
    unsupportedFileDesc: "Sila muat naik imej JPEG, PNG, atau WebP.",
    fileTooLarge: "Fail Terlalu Besar",
    fileTooLargeDesc: "Sila muat naik imej yang lebih kecil daripada 10MB.",
    totalExpenses: "Jumlah Perbelanjaan",
    pendingVouchers: "Baucar Belum Selesai",
    aiOptimizations: "Pengoptimuman AI",
    recentActivity: "Aktiviti Terkini",
    aiInsights: "Wawasan AI",
    expenditure: "Perbelanjaan",
    taxDeductibility: "Potongan Cukai",
    weekly: "Mingguan",
    annually: "Tahunan",
    taxFiling: "Fail Cukai LHDN (e-B)",
    daysLeft: "Hari Tinggal",
    actionRequired: "Tindakan Diperlukan",
    startSession: "Mula Sesi Suara",
    establishingLink: "Menetapkan Pautan...",
    listening: "Mendengar & Menonton...",
    speaking: "Gemini sedang bercakap...",
    connect: "Sambung Ejen",
    endSession: "Tamat Sesi",
    liveLogs: "Log Langsung",
    spatialAwareness: "Kesedaran Ruang Aktif",
    generalApiConfig: "Konfigurasi API Umum",
    apiKeyLabel: "Kunci API Google Gemini",
    apiKeyDesc: "Kunci induk ini membolehkan semua ciri AI termasuk OCR, Ejen Langsung dan Editor Imej.",
    saveConnect: "Simpan & Sambung",
    serviceStatus: "Status Perkhidmatan",
    active: "Aktif",
    inactive: "Tidak Aktif",
    ocrEngine: "Enjin OCR",
    advisorChat: "Sembang Penasihat",
    uploadImage: "Muat Naik Imej",
    editorPrompt: "Prom Editor",
    enableTranslation: "Dayakan Terjemahan",
    targetLanguage: "Bahasa Sasaran",
    generateEdit: "Jana Edit",
    generateTranslate: "Jana & Terjemah",
    downloadResult: "Muat Turun Hasil"
  },
  zh: {
    dashboard: "仪表板",
    generator: "凭单生成器",
    history: "历史记录",
    lhdnLetter: "LHDN信函",
    aiAdvisor: "AI顾问",
    liveAgent: "实时代理",
    receiptEditor: "收据编辑器",
    settings: "设置",
    appTitle1: "TUNAI",
    appTitle2: "CUKAI",
    newVoucher: "新现金凭单",
    newVoucherDesc: "使用AI辅助生成新的付款凭单",
    uploadReceipt: "上传收据",
    readAloud: "朗读",
    companyInfo: "公司信息",
    companyName: "公司名称",
    regNo: "注册号",
    address: "地址",
    tel: "电话",
    email: "电子邮件",
    voucherDetails: "凭单详情",
    voucherNo: "凭单编号",
    voucherDate: "凭单日期",
    category: "类别",
    payeeInfo: "收款人及付款信息",
    payeeName: "收款人姓名",
    payeeIc: "收款人身份证/注册号",
    paymentMethod: "付款方式",
    bankName: "银行名称",
    desc: "描述",
    dictate: "口述",
    stop: "停止",
    aiSummarize: "AI摘要",
    taxCompliance: "税务合规",
    lineItems: "项目列表",
    addItem: "添加项目",
    summary: "摘要",
    totalAmount: "总金额",
    save: "保存",
    previewPdf: "预览PDF",
    downloadPdf: "下载PDF",
    complianceProgress: "合规进度",
    scanFailed: "扫描失败",
    unclearDoc: "文件不清晰",
    unclearDocDesc: "无法识别清晰的文本。请确保图像光线充足且清晰。",
    authFailed: "验证失败",
    authFailedDesc: "API密钥无效或丢失。请检查设置。",
    quotaExceeded: "超出配额",
    quotaExceededDesc: "您已达到API请求限制。请稍后再试。",
    serviceUnavailable: "服务不可用",
    serviceUnavailableDesc: "AI服务当前繁忙。请稍后再试。",
    connError: "连接错误",
    connErrorDesc: "无法连接到服务器。请检查您的互联网连接。",
    contentFiltered: "内容被过滤",
    contentFilteredDesc: "图像因安全原因被过滤。请尝试其他图像。",
    processingError: "处理错误",
    processingErrorDesc: "发生意外错误。请重试。",
    unsupportedFile: "不支持的文件",
    unsupportedFileDesc: "请上传JPEG，PNG或WebP图像。",
    fileTooLarge: "文件太大",
    fileTooLargeDesc: "请上传小于10MB的图像。",
    totalExpenses: "总支出",
    pendingVouchers: "待处理凭单",
    aiOptimizations: "AI优化",
    recentActivity: "最近活动",
    aiInsights: "AI见解",
    expenditure: "支出",
    taxDeductibility: "税收抵扣",
    weekly: "每周",
    annually: "每年",
    taxFiling: "LHDN报税 (e-B)",
    daysLeft: "剩余天数",
    actionRequired: "需要行动",
    startSession: "开始语音会话",
    establishingLink: "建立连接...",
    listening: "正在听和看...",
    speaking: "Gemini正在说话...",
    connect: "连接实时代理",
    endSession: "结束会话",
    liveLogs: "实时日志",
    spatialAwareness: "空间感知已激活",
    generalApiConfig: "通用API配置",
    apiKeyLabel: "Google Gemini API密钥",
    apiKeyDesc: "此主密钥启用所有AI功能，包括OCR，实时代理和图像编辑。",
    saveConnect: "保存并连接",
    serviceStatus: "服务状态",
    active: "活跃",
    inactive: "不活跃",
    ocrEngine: "OCR引擎",
    advisorChat: "顾问聊天",
    uploadImage: "上传图片",
    editorPrompt: "编辑提示",
    enableTranslation: "启用翻译",
    targetLanguage: "目标语言",
    generateEdit: "生成编辑",
    generateTranslate: "生成并翻译",
    downloadResult: "下载结果"
  },
  // ... other languages would follow same pattern, defaulting to EN for brevity in this specific update block to avoid massive file
  yue: { dashboard: "儀表板", generator: "傳票生成器", history: "紀錄", lhdnLetter: "LHDN信件", aiAdvisor: "AI顧問", liveAgent: "即時助手", receiptEditor: "收據編輯", settings: "設定", appTitle1: "TUNAI", appTitle2: "CUKAI" },
  ja: { dashboard: "ダッシュボード", generator: "伝票作成", history: "履歴", lhdnLetter: "LHDNレター", aiAdvisor: "AIアドバイザー", liveAgent: "ライブエージェント", receiptEditor: "領収書編集", settings: "設定", appTitle1: "TUNAI", appTitle2: "CUKAI" },
  id: { dashboard: "Dasbor", generator: "Pembuat Voucher", history: "Riwayat", lhdnLetter: "Surat LHDN", aiAdvisor: "Penasihat AI", liveAgent: "Agen Langsung", receiptEditor: "Editor Tanda Terima", settings: "Pengaturan", appTitle1: "TUNAI", appTitle2: "CUKAI" },
  ru: { dashboard: "Панель", generator: "Генератор ваучеров", history: "История", lhdnLetter: "Письмо LHDN", aiAdvisor: "AI Советник", liveAgent: "Живой агент", receiptEditor: "Редактор чеков", settings: "Настройки", appTitle1: "TUNAI", appTitle2: "CUKAI" },
  de: { dashboard: "Dashboard", generator: "Beleg-Generator", history: "Verlauf", lhdnLetter: "LHDN-Brief", aiAdvisor: "KI-Berater", liveAgent: "Live-Agent", receiptEditor: "Beleg-Editor", settings: "Einstellungen", appTitle1: "TUNAI", appTitle2: "CUKAI" }
};

// Fallback logic for missing keys
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<LanguageCode>('en');

  const t = (key: string) => {
    // 1. Try selected language
    // 2. Try English
    // 3. Return key as fallback
    return dictionaries[language]?.[key] || dictionaries['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
